### ISSUE TITLE
提个建议,可以做一个,汉字转为拼音来分组,而不是手工去写.

### ISSUE THREAD

**Issue by b1ueRa1n** [johnnynode/ionic-sample#2]
谢谢你的代码

**Comment by johnnynode** [comment]
@b1ueRa1n 是关于数据的分组嘛，那些数据都是从后台接口中调出来的，然后通过聚类实现的分组。因为后端定义的数据模型不一样，在返回给前端的时候是并未经过太多处理, 其实前台或者后台都可以对数据进行处理，组成合理的结构方便展示就行。
